alunos/urls.py
from django.contrib.auth import login
from django.urls import path, include
from alunos import views

app_name = 'alunos'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('cadastrar/', views.cadastrar, name='cadastrar')
]

angominedu/urls.py
from django.urls import path
from angominedu import views

app_name = 'angominedu'
urlpatterns = [
    path('', views.index, name='index')
]

matricula/urls.py
from django.urls import path
from matricula import views

app_name = 'matricula'
urlpatterns = [
    path('', views.index, name='index')
]

set/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('matricula/', include('matricula.urls')),
    path('aluno/', include('alunos.urls')),
    path('', include('angominedu.urls'))
]

angominedu/models.py
from django.db import models

# Create your models here.

matricula/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


# Create your models here.
class Aluno(models.Model):
    PROVINCIAS = (('Bengo', 'Bengo'), ('Benguela', 'Benguela'), ('Bie', 'Bie'), ('Cabinda', 'Cabinda'), ('Cuando Cubango', 'Cuando Cubango'),
                  ('Cuanza Norte', 'Cuanza Norte'), ('Cuanza Sul', 'Cuanza Sul'), ('Cunene', 'Cunene'), ('Huambo', 'Huambo'), ('Huila', 'Huila'),
                  ('Luanda', 'Luanda'), ('Lunda Norte', 'Lunda Norte'), ('Lunda Sul', 'Lunda Sul'), ('Malanje', 'Malanje'), ('Moxico', 'Moxico'),
                  ('Namibe', 'Namibe'), ('Uige', 'Uige'), ('Zaire', 'Zaire'), ('Outra', 'Outra (Estrangeira)'))

    id = models.IntegerField(primary_key=True, unique=True, auto_created=True)
    criador = models.ForeignKey(User, on_delete=models.CASCADE)

    nome = models.CharField(max_length=20)
    sobrenome = models.CharField(max_length=30)
    n_bi = models.CharField(max_length=14, unique=True)
    data_nascimento = models.DateField(auto_now=timezone.now)
    n_contato = models.CharField(max_length=13)
    n_contato_alternativo = models.CharField(max_length=13)
    nome_pai = models.CharField(max_length=50)
    nome_mae = models.CharField(max_length=50)
    residencia = models.CharField(max_length=50)
    nacionalidade = models.CharField(max_length=20)
    naturalidade = models.CharField(max_length=30)
    provincia = models.CharField(max_length=20, choices=PROVINCIAS, default='Luanda')

    escola = models.CharField(max_length=30, help_text='O nome da escola que deseja ingressar.')
    ano_lectivo = models.CharField(max_length=4, default=2022, help_text='O ano lectivo que deseja iniciar.')

    def __str__(self):
        return f"ID-Aluno: {self.id}\n" \
               f"Nome: {self.nome} {self.sobrenome}\n" \
               f"Data Nascimento: {self.data_nascimento}\n" \
               f"Filho de: {self.nome_pai} e de: {self.nome_mae}\n" \
               f"BI/Passaporte: {self.n_bi}\n" \
               f"Nacionalidade: {self.nacionalidade}" \
               f"Naturalidade: {self.naturalidade}-{self.provincia}"

matricula/forms.py
from django import forms
from matricula.models import Aluno


class Matricula(forms.ModelForm):
    class Meta:
        model = Aluno
        fields = ['nome', 'sobrenome', 'data_nascimento', 'n_bi',
                  'n_contato', 'n_contato_alternativo', 'nome_pai', 'nome_mae',
                  'residencia', 'naturalidade', 'provincia', 'escola', 'ano_lectivo', 'nacionalidade']
        labels = {'escola': 'Nome da Escola',
                  'ano_lectivo': 'Ano lectivo',
                  'nome': 'Nome do Aluno',
                  'sobrenome': 'Sobrenome do Aluno',
                  'data_nascimento': 'Data de Nascimento',
                  'n_bi': 'Numero BI/Passaporte',
                  'nome_pai': 'Nome do Pai',
                  'nome_mae': 'Nome da Mae',
                  'nacionalidade': 'Nacionalidade',
                  'naturalidade': 'Naturalidade',
                  'provincia': 'Provincia',
                  'n_contato': 'Numero telefone',
                  'n_contato_alternativo': 'Numero telefone alternativo',
                  'residencia': 'Residencia'}

alunos/views.py
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect, render


# Create your views here.
def cadastrar(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('etudiorder:index')
    context = {'title': 'Etudi-Order | cadastro', 'form': form}
    return render(request, 'registration/cadastrar.html', context)

matricula/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'index.html')

matricula/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <script src="{% static '/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static '/js/bootstrap.js' %}"></script>
    <script src="{% static '/js/jquery-3.5.1.js' %}"></script>

    <link rel="apple-touch-icon" sizes="180x180" href="{% static '/img/favicon/apple-touch-icon.png' %}">
    <link rel="icon" sizes="32x32" href="{% static '/img/favicon/favicon-32x32.png' %}" type="image/png">
    <link rel="icon" sizes="16x16" href="{% static '/img/favicon/favicon-16x16.png' %}" type="image/png">
    <link rel="shortcut icon" href="{% static '/img/favicon/favicon.ico' %}" type="image/x-icon">
    <link rel="manifest" href="{% static '/img/favicon/site.webmanifest' %}">
    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>AngoMinEdu</title>
    {% endif %}

    {% block extra_head %}{% endblock extra_head %}
</head>
<body class="bg-dark">
<nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <a class="navbar-brand" href="{% url 'angominedu:index' %}">Angola - Ministerio da Educacao</a>

    <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarCollapse"
            aria-controls="navbarCollapse"
            aria-expanded="false"
            aria-label="Toggle navigation"
    >
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url ':'%}" title=""></a>
            </li>
        </ul>

        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <span class="navbar-text"><b>Olaa, {{ user.username }}!</b> -</span>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url ':logout' %}">Terminar sessao</a>
            </li>
            {% else %}
            <li class="nav-item">
                <span class="navbar-text"><b>Olaa, Companheiro!</b> -</span>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url ':login' %}">Inicie sessao</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url ':cadastrar' %}">Cadastre-se</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>
<main role="main" class="container bg-light" style="padding: 10px; border-radius: 5px;">
    <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
    </div>
    <div>{% block content %}{% endblock content %}</div>
</main>
</body>
</html>

matricula/templates/index.html
{% extends 'base.html' %}

{% block extra_head %}{% endblock extra_head %}

{% block page_header %}{% endblock page_header %}

{% block content %}{% endblock content %}